#!/bin/bash
#PBS -N merge_vcfs
#PBS -j oe
#PBS -m ae
#PBS -l nodes=1
#PBS -l ncpus=16
#PBS -l mem=100gb
#PBS -l walltime=48:00:00
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths to samtools"
export PATH=$PATH:/home/jwestaway/pk_pipeline/tools/bcftools-1.13/

echo "---------------------------------------"
echo 'Change to working directory and set env variables'
cd /home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus/

echo "---------------------------------------"
echo 'Execute bcftools merge'
bcftools merge --threads 15 --force-samples -o merged_GATK_samtools_variants.vcf.gz GATK/Genotyped.vcf.gz samtools/PK_samtools.raw.vcf.gz

echo "---------------------------------------"
echo 'Finished' 