#!/bin/bash
#PBS -N fastqc
#PBS -j oe
#PBS -m ae
#PBS -l nodes=1
#PBS -l ncpus=11
#PBS -l mem=40gb
#PBS -l walltime=24:00:00
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Export path to fastqc"
export PATH=$PATH:/usr/local/FastQC

echo "---------------------------------------"
echo "Change to current working directory"
cd pk_pipeline

echo "---------------------------------------"
echo "Set environment variable"
INPUTDIR="ZB_100/pk_data/subset/"
OUTDIR="ZB_100/outputs/fastqc/"
mkdir $OUTDIR

echo "---------------------------------------"
echo "Execute fastqc"
fastqc -t 10 -o $OUTDIR $INPUTDIR/*.fq.gz

echo "---------------------------------------"
echo "Finsihed!"