#!/bin/bash
#PBS -N trim
#PBS -j oe
#PBS -m ae
#PBS -l nodes=1
#PBS -l ncpus=21
#PBS -l mem=200gb
#PBS -l walltime=72:00:00
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Export paths and load modules"
export PATH=$PATH:/usr/local/singularity/latest/bin
export PATH=$PATH:/usr/local/parallel_20171222/bin/

echo "---------------------------------------"
echo 'Change to current working directory' 
cd pk_pipeline

echo "---------------------------------------"
echo 'Set environment vars'
OUTDIR="ZB_100/outputs/trimmed"
INPUTDIR="ZB_100/pk_data/subset"
mkdir -p $OUTDIR

echo "---------------------------------------"
echo 'Exectue trim_galore for quality and adapter trimming'
parallel -j20 --xapply singularity exec ~/pk_pipeline/tools/singularity/trim-galore_0.6.4.sif trim_galore --illumina --paired --fastqc -o $OUTDIR ::: $INPUTDIR/*1.fq.gz ::: $INPUTDIR/*2.fq.gz

echo "---------------------------------------"
echo "Finsihed!"