#!/bin/bash
#PBS -N Map_Stats_ZB
#PBS -j oe
#PBS -m ae
#PBS -l nodes=1
#PBS -l ncpus=21
#PBS -l mem=100gb
#PBS -l walltime=8:00:00
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths to bbmap and samtools"
export Path=$PATH:/home/jwestaway/pk_pipeline/tools/bbmap
export PATH=$PATH:/usr/local/miniconda3/envs/assembly/bin/  
export PATH=$PATH:/usr/local/miniconda3/pkgs/quast-5.0.2-py37pl526hb5aa323_2/lib/python3.7/site-packages/quast_libs/sambamba
module load java/1.8.0_171

echo "---------------------------------------"
echo 'Alignment - direct to Pk'

echo "---------------------------------------"
echo 'Change to working directory and set env variables'
cd /home/jwestaway/pk_pipeline/ZB_100/outputs/direct_alignment/
PILEUP="/home/jwestaway/pk_pipeline/tools/bbmap/pileup.sh"

echo "---------------------------------------"
echo 'Exectue samtools & bbmap'
for i in *.bam
do
samtools view -h --threads 20 $i | $PILEUP in=stdin 2> ${i%.bam}.mapstats
done 

echo "---------------------------------------"
echo 'Alignment - to Hg'

echo "---------------------------------------"
echo 'Change to working directory and set env variables'
cd /home/jwestaway/pk_pipeline/ZB_100/outputs/hg_removed_alignment/sortedbam/

echo "---------------------------------------"
echo 'Exectue samtools & bbmap'
for i in *.bam
do
samtools view -h --threads 20 $i | $PILEUP in=stdin 2> ${i%.bam}.mapstats
done 

echo "---------------------------------------"
echo 'Alignment - to Pk post Hg removal'

echo "---------------------------------------"
echo 'Change to working directory and set env variables'
cd /home/jwestaway/pk_pipeline/ZB_100/outputs/hg_removed_alignment/pk_alignment/

echo "---------------------------------------"
echo 'Exectue samtools & bbmap'
for i in *.bam
do
samtools view -h --threads 20 $i | $PILEUP in=stdin 2> ${i%.bam}.mapstats
done 

echo "---------------------------------------"
echo "Finsihed!"