#!/bin/bash
#PBS -N Consensus_var
#PBS -j oe
#PBS -m ae
#PBS -l nodes=1
#PBS -l ncpus=30
#PBS -l mem=300gb
#PBS -l pmem=300gb
#PBS -l file=200gb
#PBS -l walltime=8:00:00
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths to bcftools and miniconda, load the R module, change to working directory and create an output directory"
export PATH=$PATH:/home/jwestaway/pk_pipeline/tools/bcftools-1.13/
module load software/R_3.6.2
cd /home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus/

echo "---------------------------------------"
echo "Exectute bcftools to select variants that pass a specific threshold"
bcftools query -f '%CHROM %POS %ID %REF %ALT [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' /home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus/GATK/Genotyped.vcf.gz > GATK_query.tsv
bcftools query -f '%CHROM %POS %ID %REF %ALT [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' /home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus/samtools/PK_samtools_variants_only_header.raw.vcf.gz > samtools_query.tsv

echo "---------------------------------------"
echo "Execute R script to get consensus variants and stats"
source /usr/local/miniconda3/etc/profile.d/conda.sh
conda activate R_3.6.2
Rscript /home/jwestaway/pk_pipeline/ZB_100/scripts/14_Consensus_vcf/vcf_wrangle_2.R
conda deactivate

echo "---------------------------------------"
echo "Use vcf_variant_names to filter the original merged vcf for variants called by both tools"

echo "---------------------------------------"
echo "Create a seperate file that contains all the header information for the vcf"
zcat merged_variants_only.vcf.gz | head -n 85 > vcf_head.vcf 

echo "---------------------------------------"
echo "Remove the column names from the variant names document to create a list of grep patterns"
tail -n +2 vcf_variant_names.tsv > grep_patterns.txt 

echo "---------------------------------------"
echo "Change default language to ASCII - fewer characters than UTF8"
LC_ALL=C

echo "---------------------------------------"
echo "Filter for variants from the original vcf that are called by both callers by using grep to match patterns created above" 
bcftools view merged_variants_only.vcf.gz | fgrep -f grep_patterns.txt - > filtered.vcf

echo "---------------------------------------"
echo "Concatenate the vcf header in the variants called by both callers"
cat vcf_head.vcf filtered.vcf > PK_consensus.vcf

echo "---------------------------------------"
echo "Finished "
