#!/bin/bash
#PBS -N Map_Stats_Test
#PBS -j oe
#PBS -m ae
#PBS -l nodes=1
#PBS -l ncpus=21
#PBS -l mem=100gb
#PBS -l walltime=12:00:00
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths to bbmap and samtools"
export Path=$PATH:/home/jwestaway/pk_pipeline/tools/bbmap
export PATH=$PATH:/usr/local/miniconda3/envs/assembly/bin/  
export PATH=$PATH:/usr/local/miniconda3/pkgs/quast-5.0.2-py37pl526hb5aa323_2/lib/python3.7/site-packages/quast_libs/sambamba
module load java/1.8.0_171

echo "---------------------------------------"
echo 'MAP STATS'

echo "---------------------------------------"
echo 'Change to working directory and set env variables'
cd /home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus/GATK/PK_SB_DNA_006_DKDL210002135-1a_HWHGKDSXY_L4
PILEUP="/home/jwestaway/pk_pipeline/tools/bbmap/pileup.sh"

echo "---------------------------------------"
echo 'Exectue samtools & bbmap'
samtools view -h --threads 20 PK_SB_DNA_006_DKDL210002135-1a_HWHGKDSXY_L4.dupmarked.realigned.recal.bam | \
    $PILEUP in=stdin 2> PK_SB_DNA_006_DKDL210002135-1a_HWHGKDSXY_L4.dupmarked.realigned.recal.mapstats

samtools view -h --threads 20 PK_SB_DNA_006_DKDL210002135-1a_HWHGKDSXY_L4.dupmarked.reheader.bam | \
    $PILEUP in=stdin 2> PK_SB_DNA_006_DKDL210002135-1a_HWHGKDSXY_L4.dupmarked.reheader.mapstats

echo "---------------------------------------"
echo "Read Depth"

echo "---------------------------------------"
echo "Define paths to samtools"
export PATH=$PATH:/usr/local/miniconda3/envs/assembly/bin/

echo "---------------------------------------"
echo 'Change to working directory and set env variables'
BED='/home/jwestaway/pk_pipeline/ref_genomes/PKA1H1/strain_A1_H.1.Icor.fasta.bed'

echo "---------------------------------------"
echo 'Exectue samtools depth'
samtools depth -a -b $BED -f filenames.txt -o bam_pre_test_summary.depths

echo "---------------------------------------"
echo "Finsihed!"