#!/bin/bash
#PBS -N QC_Trim
#PBS -j oe
#PBS -m ae
#PBS -l nodes=1
#PBS -l ncpus=30
#PBS -l mem=250gb
#PBS -l walltime=72:00:00
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Create paths to required software"
export PATH=$PATH:/usr/local/singularity/latest/bin/
export PATH=$PATH:/usr/local/FastQC/
export PATH=$PATH:/usr/local/parallel_20171222/bin/

echo "---------------------------------------"
echo 'Change to working directory' 
cd /home/jwestaway/pk_pipeline/Initial_Pk_subset

echo "---------------------------------------"
echo "Set environment variable"
MULTIQC="/home/jwestaway/pk_pipeline/tools/singularity/multiqc_v0.1.9.sif"
QC_OUTDIR="/home/jwestaway/pk_pipeline/Initial_Pk_subset/outputs/batch6/fastqc"
TRIM_OUTDIR="/home/jwestaway/pk_pipeline/Initial_Pk_subset/outputs/batch6/trimmed_fastq"
mkdir /home/jwestaway/pk_pipeline/Initial_Pk_subset/outputs/batch6/
mkdir $QC_OUTDIR
mkdir $TRIM_OUTDIR

echo "---------------------------------------"
echo "Unzip batch"
unzip -j "data/ZB/X401SC21032211-Z01-F001_4.zip" "X401SC21032211-Z01-F001_4/*/*fq.gz" -d "data/batch6"

echo "---------------------------------------"
echo "QC"
fastqc -t 30 -o $QC_OUTDIR data/batch6/*.fq.gz
singularity exec $MULTIQC multiqc $QC_OUTDIR/. -o $QC_OUTDIR

echo "---------------------------------------"
echo "Trim"
parallel -j30 --xapply singularity exec ~/pk_pipeline/tools/singularity/trim-galore_0.6.4.sif trim_galore --illumina --paired --fastqc -o $TRIM_OUTDIR ::: data/batch6/*1.fq.gz ::: data/batch6/*2.fq.gz

echo "---------------------------------------"
echo "QC on Trimmed"
singularity exec $MULTIQC multiqc $TRIM_OUTDIR/. -o $TRIM_OUTDIR

echo "---------------------------------------"
echo "Clean up"
rm -f data/batch6/*fq.gz

echo "---------------------------------------"
echo "Finished"