#!/bin/bash
#PBS -N Wrangle_test
#PBS -j oe
#PBS -m ae
#PBS -l nodes=1
#PBS -l ncpus=21
#PBS -l mem=100gb
#PBS -l pmem=100gb
#PBS -l file=100gb
#PBS -l walltime=24:00:00
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Load the R module, change to working directory"
module load software/R_3.6.2
cd /home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus/

echo "---------------------------------------"
echo "Execute R script to get consensus variants and stats"
source /usr/local/miniconda3/etc/profile.d/conda.sh
conda activate R_3.6.2
Rscript /home/jwestaway/pk_pipeline/ZB_100/scripts/14_Consensus_vcf/vcf_wrangle.R
conda deactivate

echo "---------------------------------------"
echo "Finished"