#!/bin/bash
#PBS -N Filter_variants
#PBS -j oe
#PBS -m ae
#PBS -l nodes=1
#PBS -l ncpus=16
#PBS -l mem=50gb
#PBS -l walltime=24:00:00
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "---------------------------------------"
echo 'Change to working directory and set env variables'
OUTDIR="/home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus/filtering_tests/Vivax/adjusted"
PICARD="/usr/local/miniconda3/pkgs/picard-2.21.9-0/share/picard-2.21.9-0/picard.jar"
INDEXTDIR="/home/jwestaway/pk_pipeline/ref_genomes/PKA1H1/fasta/strain_A1_H.1.Icor.fasta"

cd /home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus

echo "------------------------------------------------------------------------------------------------------------------------------------------------------------"
echo 'QD'
echo "------------------------------------------------------------------------------------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'FILTER'
echo "---------------------------------------"

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V GVCFall_SNPs.vcf \
    -filter "QD < 20.0" --filter-name "QD2" \
    -filter "FS > 14.63418" --filter-name "FS60" \
    -filter "MQ < 51.6" --filter-name "MQ40" \
    -O $OUTDIR/QD_snps_filtered.vcf

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V GVCFall_INDELs.vcf \
    -filter "QD < 20.0" --filter-name "QD2" \
    -filter "FS > 14.63418" --filter-name "FS60" \
    -filter "MQ < 51.6" --filter-name "MQ40" \
    -O $OUTDIR/QD_indels_filtered.vcf

echo "---------------------------------------"
echo 'Query data for download/comparison'
echo "---------------------------------------"

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/QD_snps_filtered.vcf | fgrep 'PASS' > $OUTDIR/QD_SNPs.tsv
bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/QD_indels_filtered.vcf | fgrep 'PASS' > $OUTDIR/QD_indels.tsv


echo "------------------------------------------------------------------------------------------------------------------------------------------------------------"
echo 'FS'
echo "------------------------------------------------------------------------------------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'FILTER'
echo "---------------------------------------"

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V GVCFall_SNPs.vcf \
    -filter "QD < 12.43" --filter-name "QD2" \
    -filter "FS > 2.0" --filter-name "FS60" \
    -filter "MQ < 51.6" --filter-name "MQ40" \
    -O $OUTDIR/FS_snps_filtered.vcf

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V GVCFall_INDELs.vcf \
    -filter "QD < 12.43" --filter-name "QD2" \
    -filter "FS > 2.0" --filter-name "FS60" \
    -filter "MQ < 51.6" --filter-name "MQ40" \
    -O $OUTDIR/FS_indels_filtered.vcf

echo "---------------------------------------"
echo 'Query data for download/comparison'
echo "---------------------------------------"

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/FS_snps_filtered.vcf | fgrep 'PASS' > $OUTDIR/FS_SNPs.tsv
bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/FS_indels_filtered.vcf | fgrep 'PASS' > $OUTDIR/FS_indels.tsv

echo "------------------------------------------------------------------------------------------------------------------------------------------------------------"
echo 'MQ'
echo "------------------------------------------------------------------------------------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'FILTER'
echo "---------------------------------------"

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V GVCFall_SNPs.vcf \
    -filter "QD < 12.43" --filter-name "QD2" \
    -filter "FS > 14.63418" --filter-name "FS60" \
    -filter "MQ < 59.0" --filter-name "MQ40" \
    -O $OUTDIR/MQ_snps_filtered.vcf

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V GVCFall_INDELs.vcf \
    -filter "QD < 12.43" --filter-name "QD2" \
    -filter "FS > 14.63418" --filter-name "FS60" \
    -filter "MQ < 59.0" --filter-name "MQ40" \
    -O $OUTDIR/MQ_indels_filtered.vcf

echo "---------------------------------------"
echo 'Query data for download/comparison'
echo "---------------------------------------"

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/MQ_snps_filtered.vcf | fgrep 'PASS' > $OUTDIR/MQ_SNPs.tsv
bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/MQ_indels_filtered.vcf | fgrep 'PASS' > $OUTDIR/MQ_indels.tsv

echo "------------------------------------------------------------------------------------------------------------------------------------------------------------"
echo 'ALL'
echo "------------------------------------------------------------------------------------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'FILTER'
echo "---------------------------------------"

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V GVCFall_SNPs.vcf \
    -filter "QD < 20.0" --filter-name "QD2" \
    -filter "FS > 2.0" --filter-name "FS60" \
    -filter "MQ < 59.0" --filter-name "MQ40" \
    -O $OUTDIR/ALL_snps_filtered.vcf

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V GVCFall_INDELs.vcf \
    -filter "QD < 20.0" --filter-name "QD2" \
    -filter "FS > 2.0" --filter-name "FS60" \
    -filter "MQ < 59.0" --filter-name "MQ40" \
    -O $OUTDIR/ALL_indels_filtered.vcf

echo "---------------------------------------"
echo 'Query data for download/comparison'
echo "---------------------------------------"

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/ALL_snps_filtered.vcf | fgrep 'PASS' > $OUTDIR/ALL_SNPs.tsv
bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/ALL_indels_filtered.vcf | fgrep 'PASS' > $OUTDIR/ALL_indels.tsv

echo "------------------------------------------------------------------------------------------------------------------------------------------------------------"
echo 'ORIGINAL'
echo "------------------------------------------------------------------------------------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'FILTER'
echo "---------------------------------------"

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V GVCFall_SNPs.vcf \
    -filter "QD < 12.43" --filter-name "QD2" \
    -filter "FS > 14.63418" --filter-name "FS60" \
    -filter "MQ < 51.6" --filter-name "MQ40" \
    -O $OUTDIR/Vivax_snps_filtered.vcf

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V GVCFall_INDELs.vcf \
    -filter "QD < 12.43" --filter-name "QD2" \
    -filter "FS > 14.63418" --filter-name "FS60" \
    -filter "MQ < 51.6" --filter-name "MQ40" \
    -O $OUTDIR/Vivax_indels_filtered.vcf

echo "---------------------------------------"
echo 'Query data for download/comparison'
echo "---------------------------------------"

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/Vivax_snps_filtered.vcf | fgrep 'PASS' > $OUTDIR/Vivax_SNPs.tsv
bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/Vivax_indels_filtered.vcf | fgrep 'PASS' > $OUTDIR/Vivax_indels.tsv

echo "---------------------------------------------------------------------------------------------------------------------"
echo 'Tidy up'
echo "---------------------------------------------------------------------------------------------------------------------"
cd $OUTDIR
wc -l *tsv > adjusted_filters_4.tsv
rm *filtered*

echo "---------------------------------------"
echo 'Finished'
