#!/bin/bash
#PBS -N Filter_variants_vivax
#PBS -j oe
#PBS -m ae
#PBS -l nodes=1
#PBS -l ncpus=11
#PBS -l mem=50gb
#PBS -l walltime=24:00:00
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "---------------------------------------"
echo 'Change to working directory and set env variables'
OUTDIR="/home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus/filtering_tests/Vivax"
PICARD="/usr/local/miniconda3/pkgs/picard-2.21.9-0/share/picard-2.21.9-0/picard.jar"
INDEXTDIR="/home/jwestaway/pk_pipeline/ref_genomes/PKA1H1/fasta/strain_A1_H.1.Icor.fasta"
cd /home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus

echo "---------------------------------------"
echo 'filter snps'
/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V GVCFall_SNPs.vcf \
    -filter "QD < 12.43" --filter-name "QD2" \
    -filter "FS > 14.63418" --filter-name "FS60" \
    -filter "MQ < 51.6" --filter-name "MQ40" \
    -O $OUTDIR/snps_filtered.vcf


echo "---------------------------------------"
echo 'filter indels'
/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V GVCFall_INDELs.vcf \
    -filter "QD < 12.43" --filter-name "QD2" \
    -filter "FS > 14.63418" --filter-name "FS60" \
    -filter "MQ < 51.6" --filter-name "MQ40" \
    -O $OUTDIR/indels_filtered.vcf


echo "---------------------------------------"
echo 'Make diagnostic tables for Variants Scores - snps'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantsToTable \
    -R $INDEXTDIR \
    -V $OUTDIR/snps_filtered.vcf \
    -F CHROM -F POS -F QUAL -F QD -F DP -F MQ -F GQ -F MQRankSum -F FS -F ReadPosRankSum -F SOR \
    -O $OUTDIR/GVCFall_SNPs.table


echo "---------------------------------------"
echo 'Make diagnostic tables for Variants Scores - indels'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantsToTable \
    -R $INDEXTDIR \
    -V $OUTDIR/indels_filtered.vcf \
    -F CHROM -F POS -F QUAL -F QD -F DP -F MQ -F GQ -F MQRankSum -F FS -F ReadPosRankSum -F SOR \
    -O $OUTDIR/GVCFall_INDELs.table


echo "---------------------------------------"
echo 'Query data for download/comparison'
echo "---------------------------------------"

echo "---------------------------------------"
echo "SNPs"

echo "---------------------------------------"
echo "Exectute bcftools to select variants that pass a specific threshold: FMT/GQ>30 & FMT/DP>10"
bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered.vcf | fgrep 'PASS' > $OUTDIR/SNPs.tsv

echo "---------------------------------------"
echo "Indels"

echo "---------------------------------------"
echo "Exectute bcftools to select variants that pass a specific threshold: FMT/GQ>30 & FMT/DP>10"
bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/indels_filtered.vcf | fgrep 'PASS' > $OUTDIR/indels.tsv






echo "---------------------------------------"
echo "Filter applied to pre-merged tool-specific data"
echo "---------------------------------------"




echo "---------------------------------------"
echo 'GATK'


echo "---------------------------------------"
echo 'filter snps'
/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V GATK/GVCFall_SNPs_GATK.vcf \
    -filter "QD < 12.43" --filter-name "QD2" \
    -filter "FS > 14.63418" --filter-name "FS60" \
    -filter "MQ < 51.6" --filter-name "MQ40" \
    -O $OUTDIR/snps_filtered_GATK.vcf


echo "---------------------------------------"
echo 'filter indels'
/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V GATK/GVCFall_INDELs_GATK.vcf \
    -filter "QD < 12.43" --filter-name "QD2" \
    -filter "FS > 14.63418" --filter-name "FS60" \
    -filter "MQ < 51.6" --filter-name "MQ40" \
    -O $OUTDIR/indels_filtered_GATK.vcf

echo "---------------------------------------"
echo 'Make diagnostic tables for Variants Scores - snps'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantsToTable \
    -R $INDEXTDIR \
    -V $OUTDIR/snps_filtered_GATK.vcf \
    -F CHROM -F POS -F QUAL -F QD -F DP -F MQ -F GQ -F MQRankSum -F FS -F ReadPosRankSum -F SOR \
    -O $OUTDIR/GVCFall_SNPs_GATK.table


echo "---------------------------------------"
echo 'Make diagnostic tables for Variants Scores - indels'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantsToTable \
    -R $INDEXTDIR \
    -V $OUTDIR/indels_filtered_GATK.vcf \
    -F CHROM -F POS -F QUAL -F QD -F DP -F MQ -F GQ -F MQRankSum -F FS -F ReadPosRankSum -F SOR \
    -O $OUTDIR/GVCFall_INDELs_GATK.table

echo "---------------------------------------"
echo "Exectute bcftools to select variants"
bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_GATK.vcf | fgrep 'PASS' > $OUTDIR/SNPs_GATK.tsv

echo "---------------------------------------"
echo "Indels"

echo "---------------------------------------"
echo "Exectute bcftools to select variants"
bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/indels_filtered_GATK.vcf | fgrep 'PASS' > $OUTDIR/indels_GATK.tsv



echo "---------------------------------------"
echo 'samtools'

echo "---------------------------------------"
echo 'filter snps'
/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V samtools/GVCFall_SNPs_bcftools.vcf \
    -filter "QD < 12.43" --filter-name "QD2" \
    -filter "FS > 14.63418" --filter-name "FS60" \
    -filter "MQ < 51.6" --filter-name "MQ40" \
    -O $OUTDIR/snps_filtered_bcftools.vcf


echo "---------------------------------------"
echo 'filter indels'
/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V samtools/GVCFall_INDELs_bcftools.vcf \
    -filter "QD < 12.43" --filter-name "QD2" \
    -filter "FS > 14.63418" --filter-name "FS60" \
    -filter "MQ < 51.6" --filter-name "MQ40" \
    -O $OUTDIR/indels_filtered_bcftools.vcf

echo "---------------------------------------"
echo 'Make diagnostic tables for Variants Scores - snps'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantsToTable \
    -R $INDEXTDIR \
    -V $OUTDIR/snps_filtered_bcftools.vcf \
    -F CHROM -F POS -F QUAL -F QD -F DP -F MQ -F GQ -F MQRankSum -F FS -F ReadPosRankSum -F SOR \
    -O $OUTDIR/GVCFall_SNPs_bcftools.table


echo "---------------------------------------"
echo 'Make diagnostic tables for Variants Scores - indels'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantsToTable \
    -R $INDEXTDIR \
    -V $OUTDIR/indels_filtered_bcftools.vcf \
    -F CHROM -F POS -F QUAL -F QD -F DP -F MQ -F GQ -F MQRankSum -F FS -F ReadPosRankSum -F SOR \
    -O $OUTDIR/GVCFall_INDELs_bcftools.table

echo "---------------------------------------"
echo "Exectute bcftools to select variants"
bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_bcftools.vcf | fgrep 'PASS' > $OUTDIR/SNPs_bcftools.tsv


echo "---------------------------------------"
echo "Exectute bcftools to select variants"
bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/indels_filtered_bcftools.vcf | fgrep 'PASS' > $OUTDIR/indels_bcftools.tsv

echo "---------------------------------------"
echo 'Finished'
