#!/bin/bash
#PBS -N Variant_calling
#PBS -j oe
#PBS -m ae
#PBS -l nodes=1
#PBS -l ncpus=21
#PBS -l mem=84gb
#PBS -l walltime=72:00:00
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths"
export PATH=$PATH:/home/jwestaway/pk_pipeline/tools/bcftools-1.13/
module load software/R_3.6.2

echo "---------------------------------------"
echo "---------------------------------------"
echo 'Change to working directory and set env variables'
PICARD="/usr/local/miniconda3/pkgs/picard-2.21.9-0/share/picard-2.21.9-0/picard.jar"
INDEXTDIR="/home/jwestaway/pk_pipeline/ref_genomes/PKA1H1/fasta/strain_A1_H.1.Icor.fasta"
OUTDIR="/home/jwestaway/pk_pipeline/Initial_Pk_subset/outputs/variant_calling/consensus/updated"
INDIR="/home/jwestaway/pk_pipeline/Initial_Pk_subset/outputs/variant_calling/"

cd $OUTDIR

echo "---------------------------------------------------------------------------------------------------------------------"
echo "Create consensus VCF"
echo "---------------------------------------------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'Merge variants from the two variant callers'
bcftools merge --threads 16 --force-samples -o $OUTDIR/merged_variants_only.vcf.gz $INDIR/GATK/GATK_genotyped.vcf.gz $INDIR/bcftools/bcftools_genotyped.vcf.gz

echo "---------------------------------------"
echo "Query VCF files to get a list of 'variant IDs' from each tool"
bcftools view merged_variants_only.vcf.gz | sed -n '/#CHROM/,$p' > merged_variants_only.tsv

echo "---------------------------------------"
echo "Execute R script - performs an inner join on the 'variant IDs' above to find the overlapping variants"
source /usr/local/miniconda3/etc/profile.d/conda.sh
conda activate R_3.6.2
Rscript /home/jwestaway/pk_pipeline/Initial_Pk_subset/scripts/Updated_Consensus/vcf_wrangle_2.R
conda deactivate

echo "---------------------------------------"
echo "Create a seperate file that contains all the header information for the vcf"
bcftools view merged_variants_only.vcf.gz | sed '/#CHROM/q' > vcf_head.vcf

echo "---------------------------------------"
echo "Remove the column names from the variant names document to create a list of grep patterns"
tail -n +2 vcf_variant_names.tsv > grep_patterns.txt 

echo "---------------------------------------"
echo "Filter for variants from the original vcf that are called by both callers by using grep to match patterns created above" 
bcftools view merged_variants_only.vcf.gz | fgrep -f grep_patterns.txt - > filtered.vcf

echo "---------------------------------------"
echo "Concatenate the vcf header in the variants called by both callers"
cat vcf_head.vcf filtered.vcf > Consensus_with_duplicates.vcf

echo "---------------------------------------"
echo "Remove duplicate sample names from VCF"
/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    SelectVariants \
    -R $INDEXTDIR \
    -V Consensus_with_duplicates.vcf \
    -xl-se '2:' \
    -O Consensus.vcf
    
echo "---------------------------------------"
echo "Finished "
