#!/bin/bash
#PBS -N Unique_variants_from_tools
#PBS -j oe
#PBS -m ae
#PBS -l nodes=1
#PBS -l ncpus=30
#PBS -l mem=300gb
#PBS -l pmem=300gb
#PBS -l file=200gb
#PBS -l walltime=24:00:00
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths and set variables"
export PATH=$PATH:/home/jwestaway/pk_pipeline/tools/bcftools-1.13/
GATK="/home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus/GATK/"
bcftools="/home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus/samtools/"
cd /home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus/variants_only_test/


echo "---------------------------------------------------------------------------------------------------------------------"
echo "GATK"
echo "---------------------------------------------------------------------------------------------------------------------"

echo "---------------------------------------"
echo "Change default language to ASCII - fewer characters than UTF8"
LC_ALL=C

echo "---------------------------------------"
echo "Filter for variants from the original vcf that are called by both callers by using grep to match patterns created above" 
bcftools view $GATK/Genotyped.vcf.gz | fgrep -v -f grep_patterns.txt - > $GATK/GATK_unique.vcf


echo "---------------------------------------------------------------------------------------------------------------------"
echo "bcftools"
echo "---------------------------------------------------------------------------------------------------------------------"

echo "---------------------------------------"
echo "Filter for variants from the original vcf that are called by both callers by using grep to match patterns created above" 
bcftools view $bcftools/PK_samtools_variants_only_header.raw.vcf.gz | fgrep -v -f grep_patterns.txt - > $bcftools/bcftools_unique.vcf

echo "---------------------------------------"
echo "Finished "