#!/bin/bash
#PBS -N Filtering_unique_single_param
#PBS -j oe
#PBS -m ae
#PBS -l nodes=1
#PBS -l ncpus=21
#PBS -l mem=100gb
#PBS -l walltime=24:00:00
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths and change to working directory"
INDEXTDIR="/home/jwestaway/pk_pipeline/ref_genomes/PKA1H1/fasta/strain_A1_H.1.Icor.fasta"
PICARD="/usr/local/miniconda3/pkgs/picard-2.21.9-0/share/picard-2.21.9-0/picard.jar"
GATK="/home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus/GATK/"
samtools="/home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus/samtools/"
OUTDIR="/home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus/filtering_tests/unique/"
SUMMARY="/home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus/filtering_tests/unique/summary/"

mkdir $OUTDIR
mkdir $SUMMARY

cd /home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus


echo "---------------------------------------"
echo "GATK"


echo "---------------------------------------"
echo "SNPs"

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    SelectVariants \
    -R $INDEXTDIR \
    -V $GATK/GATK_unique.vcf \
    --select-type-to-include SNP \
    -O $OUTDIR/unique_SNPs_GATK.vcf

echo "---------------------------------------"
echo "Indels"

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    SelectVariants \
    -R $INDEXTDIR \
    -V $GATK/GATK_unique.vcf \
    --select-type-to-include INDEL \
    -O $OUTDIR/unique_INDELs_GATK.vcf


echo "---------------------------------------"
echo "samtools/bcftools"


echo "---------------------------------------"
echo "SNPs"

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    SelectVariants \
    -R $INDEXTDIR \
    -V $samtools/bcftools_unique.vcf \
    --select-type-to-include SNP \
    -O $OUTDIR/unique_SNPs_bcftools.vcf

echo "---------------------------------------"
echo "Indels"

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    SelectVariants \
    -R $INDEXTDIR \
    -V $samtools/bcftools_unique.vcf \
    --select-type-to-include INDEL \
    -O $OUTDIR/unique_INDELs_bcftools.vcf



echo "------------------------------------------------------------------------------------------------------------------------------------------------------------"
echo "FILTERING"
echo "------------------------------------------------------------------------------------------------------------------------------------------------------------"


echo "---------------------------------------------------------------------------------------------------------------------"
echo 'GATK_BP'
echo "---------------------------------------------------------------------------------------------------------------------"

echo "------------------------------------------------------------------------------------------------------------------------------------------------------------"
echo 'SNPs'
echo "------------------------------------------------------------------------------------------------------------------------------------------------------------"

echo "------------------------------------------------------------------------------"
echo 'QD'
echo "------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'GATK'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_SNPs_GATK.vcf \
    -filter "QD < 2.0" --filter-name "QD2" \
    -O $OUTDIR/snps_filtered_GATK.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_GATK.vcf | fgrep 'PASS' > $OUTDIR/SNPs_GATK_QD.tsv

echo "---------------------------------------"
echo 'samtools'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_SNPs_bcftools.vcf \
    -filter "QD < 12.43" --filter-name "QD2" \
    -O $OUTDIR/snps_filtered_bcftools.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_bcftools.vcf | fgrep 'PASS' > $OUTDIR/SNPs_bcftools_QD.tsv

echo "------------------------------------------------------------------------------"
echo 'QUAL'
echo "------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'GATK'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_SNPs_GATK.vcf \
    -filter "QUAL < 30.0" --filter-name "QUAL30" \
    -O $OUTDIR/snps_filtered_GATK.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_GATK.vcf | fgrep 'PASS' > $OUTDIR/SNPs_GATK_QUAL.tsv

echo "---------------------------------------"
echo 'samtools'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_SNPs_bcftools.vcf \
    -filter "QUAL < 30.0" --filter-name "QUAL30" \
    -O $OUTDIR/snps_filtered_bcftools.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_bcftools.vcf | fgrep 'PASS' > $OUTDIR/SNPs_bcftools_QUAL.tsv

echo "------------------------------------------------------------------------------"
echo 'SQR'
echo "------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'GATK'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_SNPs_GATK.vcf \
    -filter "SOR > 3.0" --filter-name "SOR3" \
    -O $OUTDIR/snps_filtered_GATK.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_GATK.vcf | fgrep 'PASS' > $OUTDIR/SNPs_GATK_SQR.tsv

echo "---------------------------------------"
echo 'samtools'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_SNPs_bcftools.vcf \
    -filter "SOR > 3.0" --filter-name "SOR3" \
    -O $OUTDIR/snps_filtered_bcftools.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_bcftools.vcf | fgrep 'PASS' > $OUTDIR/SNPs_bcftools_SQR.tsv

echo "------------------------------------------------------------------------------"
echo 'FS'
echo "------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'GATK'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_SNPs_GATK.vcf \
    -filter "FS > 60.0" --filter-name "FS60" \
    -O $OUTDIR/snps_filtered_GATK.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_GATK.vcf | fgrep 'PASS' > $OUTDIR/SNPs_GATK_FS.tsv

echo "---------------------------------------"
echo 'samtools'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_SNPs_bcftools.vcf \
    -filter "FS > 60.0" --filter-name "FS60" \
    -O $OUTDIR/snps_filtered_bcftools.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_bcftools.vcf | fgrep 'PASS' > $OUTDIR/SNPs_bcftools_FS.tsv

echo "------------------------------------------------------------------------------"
echo 'MQ'
echo "------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'GATK'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_SNPs_GATK.vcf \
    -filter "MQ < 40.0" --filter-name "MQ40" \
    -O $OUTDIR/snps_filtered_GATK.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_GATK.vcf | fgrep 'PASS' > $OUTDIR/SNPs_GATK_MQ.tsv

echo "---------------------------------------"
echo 'samtools'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_SNPs_bcftools.vcf \
    -filter "MQ < 40.0" --filter-name "MQ40" \
    -O $OUTDIR/snps_filtered_bcftools.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_bcftools.vcf | fgrep 'PASS' > $OUTDIR/SNPs_bcftools_MQ.tsv

echo "------------------------------------------------------------------------------"
echo 'MQRankSum'
echo "------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'GATK'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_SNPs_GATK.vcf \
    -filter "MQRankSum < -12.5" --filter-name "MQRankSum-12.5" \
    -O $OUTDIR/snps_filtered_GATK.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_GATK.vcf | fgrep 'PASS' > $OUTDIR/SNPs_GATK_MQRankSum.tsv

echo "---------------------------------------"
echo 'samtools'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_SNPs_bcftools.vcf \
    -filter "MQRankSum < -12.5" --filter-name "MQRankSum-12.5" \
    -O $OUTDIR/snps_filtered_bcftools.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_bcftools.vcf | fgrep 'PASS' > $OUTDIR/SNPs_bcftools_MQRankSum.tsv

echo "------------------------------------------------------------------------------"
echo 'ReadPosRankSum'
echo "------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'GATK'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_SNPs_GATK.vcf \
    -filter "ReadPosRankSum < -8.0" --filter-name "ReadPosRankSum-8" \
    -O $OUTDIR/snps_filtered_GATK.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_GATK.vcf | fgrep 'PASS' > $OUTDIR/SNPs_GATK_ReadPosRankSum.tsv

echo "---------------------------------------"
echo 'samtools'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_SNPs_bcftools.vcf \
    -filter "ReadPosRankSum < -8.0" --filter-name "ReadPosRankSum-8" \
    -O $OUTDIR/snps_filtered_bcftools.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_bcftools.vcf | fgrep 'PASS' > $OUTDIR/SNPs_bcftools_ReadPosRankSum.tsv


echo "------------------------------------------------------------------------------------------------------------------------------------------------------------"
echo 'INDELS'
echo "------------------------------------------------------------------------------------------------------------------------------------------------------------"

echo "------------------------------------------------------------------------------"
echo 'QD'
echo "------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'GATK'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_INDELs_GATK.vcf \
    -filter "QD < 2.0" --filter-name "QD2" \
    -O $OUTDIR/indels_filtered_GATK.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/indels_filtered_GATK.vcf | fgrep 'PASS' > $OUTDIR/indels_GATK_QD.tsv


echo "---------------------------------------"
echo 'samtools'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_INDELs_bcftools.vcf \
    -filter "QD < 2.0" --filter-name "QD2" \
    -O $OUTDIR/indels_filtered_bcftools.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/indels_filtered_bcftools.vcf | fgrep 'PASS' > $OUTDIR/indels_bcftools_QD.tsv

echo "------------------------------------------------------------------------------"
echo 'QUAL'
echo "------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'GATK'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_INDELs_GATK.vcf \
    -filter "QUAL < 30.0" --filter-name "QUAL30" \
    -O $OUTDIR/indels_filtered_GATK.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/indels_filtered_GATK.vcf | fgrep 'PASS' > $OUTDIR/indels_GATK_QUAL.tsv


echo "---------------------------------------"
echo 'samtools'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_INDELs_bcftools.vcf \
    -filter "QUAL < 30.0" --filter-name "QUAL30" \
    -O $OUTDIR/indels_filtered_bcftools.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/indels_filtered_bcftools.vcf | fgrep 'PASS' > $OUTDIR/indels_bcftools_QUAL.tsv

echo "------------------------------------------------------------------------------"
echo 'FS'
echo "------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'GATK'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_INDELs_GATK.vcf \
    -filter "FS > 200.0" --filter-name "FS200" \
    -O $OUTDIR/indels_filtered_GATK.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/indels_filtered_GATK.vcf | fgrep 'PASS' > $OUTDIR/indels_GATK_FS.tsv


echo "---------------------------------------"
echo 'samtools'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_INDELs_bcftools.vcf \
    -filter "FS > 200.0" --filter-name "FS200" \
    -O $OUTDIR/indels_filtered_bcftools.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/indels_filtered_bcftools.vcf | fgrep 'PASS' > $OUTDIR/indels_bcftools_FS.tsv

echo "------------------------------------------------------------------------------"
echo 'ReadPosRankSum'
echo "------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'GATK'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_INDELs_GATK.vcf \
    -filter "ReadPosRankSum < -20.0" --filter-name "ReadPosRankSum-20" \
    -O $OUTDIR/indels_filtered_GATK.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/indels_filtered_GATK.vcf | fgrep 'PASS' > $OUTDIR/indels_GATK_ReadPosRankSum.tsv


echo "---------------------------------------"
echo 'samtools'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_INDELs_bcftools.vcf \
    -filter "ReadPosRankSum < -20.0" --filter-name "ReadPosRankSum-20" \
    -O $OUTDIR/indels_filtered_bcftools.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/indels_filtered_bcftools.vcf | fgrep 'PASS' > $OUTDIR/indels_bcftools_ReadPosRankSum.tsv


echo "------------------------------------------------------------------------------"
echo "Clean up"
echo "------------------------------------------------------------------------------"
wc -l $OUTDIR/*tsv > $SUMMARY/GATK_BP_unique_single_param.tsv
rm $OUTDIR/*filtered*
rm $OUTDIR/*tsv



echo "---------------------------------------------------------------------------------------------------------------------"
echo 'Vivax'
echo "---------------------------------------------------------------------------------------------------------------------"

echo "------------------------------------------------------------------------------------------------------------------------------------------------------------"
echo 'SNPs'
echo "------------------------------------------------------------------------------------------------------------------------------------------------------------"

echo "------------------------------------------------------------------------------"
echo 'QD'
echo "------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'GATK'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_SNPs_GATK.vcf \
    -filter "QD < 12.43" --filter-name "QD2" \
    -O $OUTDIR/snps_filtered_GATK.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_GATK.vcf | fgrep 'PASS' > $OUTDIR/SNPs_GATK_QD.tsv

echo "---------------------------------------"
echo 'samtools'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_SNPs_bcftools.vcf \
    -filter "QD < 12.43" --filter-name "QD2" \
    -O $OUTDIR/snps_filtered_bcftools.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_bcftools.vcf | fgrep 'PASS' > $OUTDIR/SNPs_bcftools_QD.tsv

echo "------------------------------------------------------------------------------"
echo 'FS'
echo "------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'GATK'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_SNPs_GATK.vcf \
    -filter "FS > 14.63418" --filter-name "FS60" \
    -O $OUTDIR/snps_filtered_GATK.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_GATK.vcf | fgrep 'PASS' > $OUTDIR/SNPs_GATK_FS.tsv

echo "---------------------------------------"
echo 'samtools'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_SNPs_bcftools.vcf \
    -filter "FS > 14.63418" --filter-name "FS60" \
    -O $OUTDIR/snps_filtered_bcftools.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_bcftools.vcf | fgrep 'PASS' > $OUTDIR/SNPs_bcftools_FS.tsv

echo "------------------------------------------------------------------------------"
echo 'MQ'
echo "------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'GATK'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_SNPs_GATK.vcf \
    -filter "MQ < 51.6" --filter-name "MQ40" \
    -O $OUTDIR/snps_filtered_GATK.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_GATK.vcf | fgrep 'PASS' > $OUTDIR/SNPs_GATK_MQ.tsv

echo "---------------------------------------"
echo 'samtools'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_SNPs_bcftools.vcf \
    -filter "MQ < 51.6" --filter-name "MQ40" \
    -O $OUTDIR/snps_filtered_bcftools.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/snps_filtered_bcftools.vcf | fgrep 'PASS' > $OUTDIR/SNPs_bcftools_MQ.tsv

echo "------------------------------------------------------------------------------------------------------------------------------------------------------------"
echo 'INDELS'
echo "------------------------------------------------------------------------------------------------------------------------------------------------------------"

echo "------------------------------------------------------------------------------"
echo 'QD'
echo "------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'GATK'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_INDELs_GATK.vcf \
    -filter "QD < 12.43" --filter-name "QD2" \
    -O $OUTDIR/indels_filtered_GATK.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/indels_filtered_GATK.vcf | fgrep 'PASS' > $OUTDIR/indels_GATK_QD.tsv


echo "---------------------------------------"
echo 'samtools'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_INDELs_bcftools.vcf \
    -filter "QD < 12.43" --filter-name "QD2" \
    -O $OUTDIR/indels_filtered_bcftools.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/indels_filtered_bcftools.vcf | fgrep 'PASS' > $OUTDIR/indels_bcftools_QD.tsv


echo "------------------------------------------------------------------------------"
echo 'FS'
echo "------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'GATK'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_INDELs_GATK.vcf \
    -filter "FS > 14.63418" --filter-name "FS60" \
    -O $OUTDIR/indels_filtered_GATK.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/indels_filtered_GATK.vcf | fgrep 'PASS' > $OUTDIR/indels_GATK_FS.tsv


echo "---------------------------------------"
echo 'samtools'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_INDELs_bcftools.vcf \
    -filter "FS > 14.63418" --filter-name "FS60" \
    -O $OUTDIR/indels_filtered_bcftools.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/indels_filtered_bcftools.vcf | fgrep 'PASS' > $OUTDIR/indels_bcftools_FS.tsv

echo 'MQ'
echo "------------------------------------------------------------------------------"

echo "---------------------------------------"
echo 'GATK'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_INDELs_GATK.vcf \
    -filter "MQ < 51.6" --filter-name "MQ40" \
    -O $OUTDIR/indels_filtered_GATK.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/indels_filtered_GATK.vcf | fgrep 'PASS' > $OUTDIR/indels_GATK_MQ.tsv


echo "---------------------------------------"
echo 'samtools'

/usr/local/jdk1.8.0_131/bin/java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar /home/jwestaway/pk_pipeline/tools/gatk-4.2.2.0/gatk-package-4.2.2.0-local.jar \
    VariantFiltration \
    -V $OUTDIR/unique_INDELs_bcftools.vcf \
    -filter "MQ < 51.6" --filter-name "MQ40" \
    -O $OUTDIR/indels_filtered_bcftools.vcf

bcftools query -f '%CHROM %POS %ID %REF %ALT %FILTER [\t%SAMPLE DP=%DP GQ=%GQ MQ=%MQ PL=%PL]\n' $OUTDIR/indels_filtered_bcftools.vcf | fgrep 'PASS' > $OUTDIR/indels_bcftools_MQ.tsv

echo "------------------------------------------------------------------------------"
echo "Clean up"
echo "------------------------------------------------------------------------------"
wc -l $OUTDIR/*tsv > $SUMMARY/VIVAX_BP_unique_single_param.tsv
rm $OUTDIR/*filtered*
rm $OUTDIR/*tsv

echo "---------------------------------------"
echo "Finished"
