#!/bin/bash
#PBS -N Annotate_variants
#PBS -j oe
#PBS -m ae
#PBS -l nodes=1
#PBS -l ncpus=16
#PBS -l mem=50gb
#PBS -l walltime=24:00:00
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "---------------------------------------"
echo 'Change to working directory and set env variables'
module load perl/5.26.0
export PATH=$PATH:/home/jwestaway/pk_pipeline/tools/ensembl-vep-release-104
OUTDIR="/home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus/variant_annotation"
GFF="/home/jwestaway/pk_pipeline/ref_genomes/PKA1H1/gff/updated_version"
FASTA="/home/jwestaway/pk_pipeline/ref_genomes/PKA1H1/fasta/strain_A1_H.1.Icor.fasta"

mkdir $OUTDIR

echo "---------------------------------------------------------------------------------------------------------------------"
echo "Sort, Zip and Index GFF"
cd $GFF

grep -v "#" PlasmoDB-55_PknowlesiA1H1.gff |\
    sed -e 's/LT727648/ordered_PKNH_01_v2/g' |\
    sed -e 's/LT727649/ordered_PKNH_02_v2/g' |\
    sed -e 's/LT727650/ordered_PKNH_03_v2/g' |\
    sed -e 's/LT727651/ordered_PKNH_04_v2/g' |\
    sed -e 's/LT727652/ordered_PKNH_05_v2/g' |\
    sed -e 's/LT727653/ordered_PKNH_06_v2/g' |\
    sed -e 's/LT727654/ordered_PKNH_07_v2/g' |\
    sed -e 's/LT727655/ordered_PKNH_08_v2/g' |\
    sed -e 's/LT727656/ordered_PKNH_09_v2/g' |\
    sed -e 's/LT727657/ordered_PKNH_10_v2/g' |\
    sed -e 's/LT727658/ordered_PKNH_11_v2/g' |\
    sed -e 's/LT727659/ordered_PKNH_12_v2/g' |\
    sed -e 's/LT727660/ordered_PKNH_13_v2/g' |\
    sed -e 's/LT727661/ordered_PKNH_14_v2/g' |\
    sed -e 's/LT727662/PKNH_MIT_v2/g' |\
    sed -e 's/LT727663/new_API_strain_A1_H.1/g' |\
    sed -e 's/protein_coding_gene/gene/g' | sort -k1,1 -k4,4n -k5,5n -t$'\t' | bgzip -c > PlasmoDB-55_PknowlesiA1H1.gff.gz

tabix -p gff PlasmoDB-55_PknowlesiA1H1.gff.gz

echo "---------------------------------------------------------------------------------------------------------------------"
echo "Change to working directoy"
cd /home/jwestaway/pk_pipeline/ZB_100/outputs/vcf_consensus/filtering_tests/Vivax/

echo "---------------------------------------------------------------------------------------------------------------------"
echo "SNPs"
vep -i snps_filtered.vcf --gff $GFF/PlasmoDB-55_PknowlesiA1H1.gff.gz --fasta $FASTA -o $OUTDIR/SNP_variant_annotation.txt --force_overwrite --everything

echo "---------------------------------------------------------------------------------------------------------------------"
echo "INDELs"
vep -i indels_filtered.vcf --gff $GFF/PlasmoDB-55_PknowlesiA1H1.gff.gz --fasta $FASTA -o $OUTDIR/Indel_variant_annotation.txt --force_overwrite --everything

echo "---------------------------------------"
echo "FINISHED"

ordered_PKNH_01_v2  41143